createdata = z => {
	return {
		language: {
			texts: {
				universe0: ["women", "women of the world", "women of the universe", "lovers",  "love wins!", "victory", "onward!", "fear not!", "industry!", "courage!", "mothers!", "solidarity!", "you can do it!", "yay", "yay", "workers", "people", "unite", "rise up", "revolution", "joy", "breathe", "cyborgs",  "photosynthesis!"],
				universe1: ["people", "universe", "universal people", "people of the universe", "yay!", "you can do it", "photosynthesis"],
				andthen0: ["and", "then", "now", "soon", "and"],
				iwas0: ["i was", "i", "i was looking", "i was looking for you", "i was", "walking"],
				letx0: ["let x", "x and", "let x equal", "let x equal x", "and x", "x equals x", "always", "and then", "i was"],
				letx1: ["Ã– x x x Ã¸ 0 Ã˜ x X x Ã¸ 0 Ã˜ xÂº3"],
				ontouch0: ["forEach", "Ã… Ã¸n t0uch Å½"],
				everymorning0: ["it was", "it was like this", "every morning", "it was", "morning", "always", "repeat"],
				everymorning1: [".. - ", " .-- .- ... ", " .-.. .. -.- . ", " - .... .. ... ", " . ...- . .-. -.-- ", " -- --- .-. -. .. -. --."],
				everymorning2: ["aXQgd2FzIGxpa2UgdGhpcyBldmVyeSBtb3JuaW5n"],
				i0: ["i0i000i0000iiii0i000i0000iii"],
				helloworld0: ["01101000", "01100101", "01101100", "01101100", "01101111", "00100000", "01110111", "01101111", "01110010", "01101100", "01100100", "hellÂº wÃ¸rld"],
				helloworld1: ["aGVsbG8gd29ybGQ="],
				holy0: ["hÃ¸ly h0LÂ¥", "hÃ¸lY H0ly Â® Ã…"],
				count0: ["#thecount â€°","0123456789iÂº","#aftercount", "#aftertime"],
				count1: ["0123456789iÂº","0123456789", "012345678", "01234"],
			},
			playlists: {
				fieldtrials: [ "universe0", "everymorning0", "universe1", "letx0" ],
				maps0: ["universe0", "andthen0", "iwas0", "letx0", "letx1", "ontouch0", "everymorning0", "everymorning1", "everymorning2", "i0", "helloworld0", "helloworld1", "holy0", "count0"],
				maps1: ["letx1", "everymorning1", "i0", "helloworld0", "count1"],
			}
		},
		colors: {
			pigments: {
				white: "#ffffff",
				warmwhite: "#fcfbe3", 
				black: "#000000", warmblack: "#191918",
				gray: "#484848", lightgray: "#888888", warmlightgray: "#656560", warmgray: "#4b4b44",
				blue: "#006699",
				red: "#9a0000",
				yellow: "ffcc00",
			},
			sets: {
				industry: ["#fcfbe3","#000000","#ffcc00","#9a0000"],
				warmindustry: ["#fcfbe3","#191918","#ffcc00","#9a0000"],
				photosynthesis: ["#fcfbe3","#000000", "#484848", "#ffcc00", "#006699"],
				warmphotosynthesis: ["#fcfbe3","#191918", "#64645a", "#ffcc00", "#006699"],
				bw: ["#000000", "fcfbe3"], 
				warmbw: ["fcfbe3", "#191918"],
				grays: ["#686868","#888888", "#484848"],
				warmgrays: ["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"],
				blues: ["#006699","#0a7293","#0a7c8e","#008888"],
				yellows: ["#fcfbe3","#ffeba9","#ffdc6e","#ffcc00"],
				bluesyellows: ["#fcfbe3","#ffeba9","#ffdc6e","#ffcc00", "#006699","#0a7293","#0a7c8e","#fcfbe3", "#64645a", "#4b4b44"],
				warmgraysred: ["#9a0000", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"],
				warmgraysblue: ["#006699", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"],
				warmgraysyellow: ["#ffcc00", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"],
				warmbwyellow: ["#ffcc00", "#fcfbe3", "#191918"], 
				warmbwred: ["#9a0000", "#fcfbe3", "#191918"],
				warmbwblue: ["#006699", "#fcfbe3", "#191918"],
				warmbwgyellow: ["#ffcc00", "#fcfbe3", "#191918", "#64645a"], 
				warmbwgred: ["#9a0000", "#fcfbe3", "#191918", "#64645a"],
				warmbwgblue: ["#006699", "#fcfbe3", "#191918", "#64645a"],
				warmwgyellow: ["#ffcc00", "#fcfbe3", "#64645a", "#979688"], 
				warmwgred: ["#9a0000", "#fcfbe3", "#64645a", "#979688"],
				warmwgblue: ["#006699", "#fcfbe3", "#64645a", "#979688"],
				bwyellow: ["#ffcc00", "#000000", "fcfbe3"],
				bwred: ["#9a0000", "#000000", "fcfbe3"],
				bwblue: ["#006699", "#000000", "fcfbe3"],
				bwgyellow: ["#ffcc00", "#000000", "fcfbe3", "#484848",],
				bwgred: ["#9a0000", "#000000", "fcfbe3", "#484848",],
				bwgblue: ["#006699", "#000000", "fcfbe3", "#484848",],
				zinnia: ["#f6f9c2", "#f5ce35", "#ed8816", "#df3420", "#da5a8b"],
			},
			playlists: {
				fieldtrials: [
					["#ffcc00", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysyellow
					["#006699", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysblue
					["#ffcc00", "#fcfbe3", "#191918"], //"warmbwyellow", 
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"],
					["#9a0000", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysred 
					["#9a0000", "#fcfbe3", "#191918"], //"warmbwred",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
					["#ffcc00", "#fcfbe3", "#191918"], //"warmbwyellow", 
					["#9a0000", "#fcfbe3", "#191918"], //"warmbwred",
					["#ffcc00", "#fcfbe3", "#191918"], //"warmbwyellow",
					["#006699", "#fcfbe3", "#191918"], //"warmbwblue",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
				],
				zinnia: [
					["#f6f9c2", "#f5ce35", "#ed8816", "#df3420", "#da5a8b", "#33689a"], //"#da5a8b" : pink, "#df3420" : red
					["#f6f9c2", "#ed8816", "#df3420", "#da5a8b"],
					["#f5ce35", "#ed8816", "#df3420"],
					["#f6f9c2", "#f5ce35", "#ed8816", "#33689a"],
				],
				chance: [ 
						['#fcfbe3','#000000','#ffcc00','#9a0000'],['#fcfbe3','#000000','#9a0000'],['#fcfbe3','#000000','#ffcc00'],['#fcfbe3','#000000'],['#fcfbe3','#000000','#ffcc00'],['#fcfbe3','#000000','#9a0000'],['#fcfbe3','#000000'] 
					],
				map3: [
					["#ffcc00", "#ffcc00","#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysyellow
					["#006699", "#006699", "#006699", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysblue
					["#fcfbe3", "#191918"], //"warmbw",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
					["#9a0000", "#9a0000", "#9a0000", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysred 
					["#9a0000", "#fcfbe3", "#191918"], //"warmbwred",
					["#fcfbe3", "#191918"], //"warmbw",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
					["#9a0000", "#fcfbe3", "#191918"], //"warmbwred",
					["#ffcc00", "#fcfbe3", "#191918"], //"warmbwyellow",
					["#006699", "#fcfbe3", "#191918"], //"warmbwblue",
					["#fcfbe3", "#191918"], //"warmbw",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
				],
				jules: [
					["#ffcc00", "#ffcc00","#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysyellow
					["#fcfbe3", "#191918"], //"warmbw",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
					["#9a0000", "#9a0000", "#9a0000", "#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgraysred 
					["#9a0000", "#fcfbe3", "#191918"], //"warmbwred",
					["#fcfbe3", "#191918"], //"warmbw",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
					["#9a0000", "#fcfbe3", "#191918"], //"warmbwred",
					["#ffcc00", "#fcfbe3", "#191918"], //"warmbwyellow",
					["#fcfbe3", "#191918"], //"warmbw",
					["#fcfbe3", "#e2e1cc", "#c9c8b5", "#b0af9e", "#979688", "#7e7d71", "#64645a", "#4b4b44", "#32322d", "#191916", "#000000"], //warmgrays
				],
			}
		},
		timesteps: [
			{ 	
				seeds: [4,8,10,12,15,16,18,30,48,60,68,88,108,148,168,3600],
				everyminute: 8, everyhour: 15, every10: 2, every15: 4, every30: 7,
				nseeds: 16
			}
		],
		sounds: {
			clips: {
				typewriter1: {url:"/data/sound/typewriter1.mp3",loaded:false,duration:2.6644897959183673,minvolume:0.6,maxvolume:0.8,buffer:{}},
				accordion: {url:"/data/sound/accordion.mp3",loaded:false,duration:0,minvolume:0.4,maxvolume:0.8,buffer:{}},
				knocking1: {url:"/data/sound/knocking1.mp3",loaded:false,duration:0,minvolume:0.4,maxvolume:0.8,buffer:{}},
				knocking2: {url:"/data/sound/knocking2.mp3",loaded:false,duration:0,minvolume:0.4,maxvolume:0.8,buffer:{}},
				birds4: {url:"/data/sound/birds4.mp3",loaded: false, duration: 0, minvolume: 0.2, maxvolume: 0.5, buffer:{}},
				birds5: {url:"/data/sound/birds5.mp3",loaded: false, duration: 0, minvolume: 0.2, maxvolume: 0.5, buffer:{}},
				birds6: {url:"/data/sound/birds6.mp3",loaded: false, duration: 0, minvolume: 0.2, maxvolume: 0.5, buffer:{}},
				silobirds: {url:"/data/sound/silobirds.mp3",loaded: false, duration: 0, minvolume: 0.2, maxvolume: 0.6, buffer:{}},
				meow: {url:"/data/sound/meow2.mp3",loaded: false, duration: 0, minvolume: 0.4, maxvolume: 0.9, buffer:{} },
				bird0: {url:"/data/sound/bird0.mp3",loaded:false,duration:6.582857142857143,minvolume:0.6,maxvolume:0.9,buffer:{}},
				bird3: {url:"/data/sound/bird3.mp3",loaded:false,duration:6.2693877551020405,minvolume:0.6,maxvolume:0.9,buffer:{}},
				bird2: {url:"/data/sound/bird2.mp3",loaded:false,duration:6.608979591836735,minvolume:0.6,maxvolume:0.9,buffer:{}},
				bird1: {url:"/data/sound/bird1.mp3",loaded:false,duration:6.608979591836735,minvolume:0.6,maxvolume:0.9,buffer:{}},
				cowbell: {url:"/data/sound/cowbell.mp3",loaded:false,duration:0,minvolume:0.3,maxvolume:0.9,buffer:{}},
				scraping: {url:"/data/sound/scraping1.mp3",loaded:false,duration:0,minvolume:0.4,maxvolume:0.9,buffer:{}},
				cello_pitch3: {url:"/data/sound/cello_pitch3.mp3",loaded:false,duration:8.986122448979591,minvolume:0.1,maxvolume:0.4,buffer:{}},
				cello_pitch4: {url:"/data/sound/cello_pitch4.mp3",loaded:false,duration:0,minvolume:0.4,maxvolume:0.9,buffer:{}},
				cello_pitch5: {url:"/data/sound/cello_pitch5.mp3",loaded:false,duration:0,minvolume:0.4,maxvolume:0.9,buffer:{}},
				sheila1: {url:"/data/sound/sheila.mp3",loaded:false,duration:0,minvolume:0.1,maxvolume:0.9,buffer:{}},
				sheila2: {url:"/data/sound/sheila1.mp3",loaded:false,duration:0,minvolume:0.1,maxvolume:0.9,buffer:{}},
				icebowedcymbal2: {url:"/data/sound/icebowedcymbal2.mp3",loaded:false,duration:10.579591836734695,minvolume:0.3,maxvolume:0.4,buffer:{}},
				fan: {url:"/data/sound/fan1.mp3",loaded:false,duration:8.150204081632653,minvolume:0.3,maxvolume:0.8,buffer:{}},
				surf: {url:"/data/sound/surf.mp3",loaded:false,duration:9.95265306122449,minvolume:0.3,maxvolume:0.8,buffer:{}},
				cello_pitch2: {url:"/data/sound/cello_pitch2.mp3",loaded:false,duration:11.206530612244897,minvolume:0.1,maxvolume:0.4,buffer:{}},
				crow: {url:"/data/sound/crow1.mp3",loaded:false,duration:11.80734693877551,minvolume:0.8,maxvolume:0.9,buffer:{}},
				bell2: {url:"/data/sound/bell2.mp3",loaded:false,duration:5.433469387755102,minvolume:0.5,maxvolume:0.8,buffer:{}},
				bell6: {url:"/data/sound/bell6.mp3",loaded:false,duration:11.885714285714286,minvolume:0.5,maxvolume:0.8,buffer:{}},
				bell11: {url:"/data/sound/bell11.mp3",loaded:false,duration:20.114285714285714,minvolume:0.5,maxvolume:0.8,buffer:{}},
				bell13: {url:"/data/sound/bell13.mp3",loaded:false,duration:20.114285714285714,minvolume:0.5,maxvolume:0.9,buffer:{}},
				longbell: {url:"/data/sound/longbell.mp3",loaded:false,duration:20.114285714285714,minvolume:0.5,maxvolume:0.8,buffer:{}},
				weatherradio1: {url:"/data/sound/weatherradio1.mp3",loaded:false,duration:12.747755102040816,minvolume:0.2,maxvolume:0.4,buffer:{}},
				train: {url:"/data/sound/train1.mp3",loaded:false,duration:12.303673469387755,minvolume:0.3,maxvolume:0.6,buffer:{}},
				icebowedvibes1: {url:"/data/sound/icebowedvibes1.mp3",loaded:false,duration:16.195918367346938,minvolume:0.1,maxvolume:0.5,buffer:{}},
				thunk: {url:"/data/sound/thunk.mp3",loaded:false,duration:21.864489795918367,minvolume:0.3,maxvolume:0.8,buffer:{}},
				birdtheme: {url:"/data/sound/birdtheme.mp3",loaded:false,duration:24.13714285714286,minvolume:0.5,maxvolume:0.9,buffer:{}},
				piano1: {url:"/data/sound/piano1.mp3",loaded:false,duration:0,minvolume:0.3,maxvolume:0.9,buffer:{}},
				kantela1: {url:"/data/sound/kantela1.mp3",loaded:false,duration:0,minvolume:0.3,maxvolume:0.9,buffer:{}},
				kantela2: {url:"/data/sound/kantela2.mp3",loaded:false,duration:0,minvolume:0.3,maxvolume:0.9,buffer:{}},
				cisterncello: {url:"/data/sound/cisterncello.mp3",loaded:false,duration:0,minvolume:0.3,maxvolume:0.9,buffer:{}},
				cello_pitch1: {url:"/data/sound/cello_pitch1.mp3",loaded:false,duration:36.12734693877551,minvolume:0.1,maxvolume:0.3,buffer:{}},
				mags1: {url: "/data/sound/magsSessionClips_1.mp3", loaded: false, duration:0, minvolume: 0.4, maxvolume: 1.0, buffer:{} },
				mags2: {url: "/data/sound/magsSessionClips_2b.mp3", loaded: false, duration:0, minvolume: 0.4, maxvolume: 1.0, buffer:{} },
				submarineecho: {url: "/data/sound/submarineecho.mp3", loaded: false, duration:0, minvolume: 0.2, maxvolume: 0.8, buffer:{} },
				clarinet1: {url:"/data/sound/clarinet1.mp3",loaded:false, duration:0, minvolume:0.5,maxvolume:0.9,buffer:{}},
			},
			instruments: {
				typewriter1: {clip: "typewriter1", minvolume: 0.6, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(4,14)/10 } },
				accordion: {clip: "accordion", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/4 } },
				knocking1: {clip: "knocking1", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(4,48)/10 } },
				knocking2: {clip: "knocking2", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(4,48)/10 } },
				cello_pitch2: {clip: "cello_pitch2", minvolume: 0.3, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				cello_pitch3: {clip: "cello_pitch3", minvolume: 0.3, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				cello_pitch4: {clip: "cello_pitch4", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				cello_pitch5: {clip: "cello_pitch5", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				sheila1: {clip: "sheila1", minvolume: 0.8, maxvolume: 1.1 },
				sheila2harmonic: {clip: "sheila2", minvolume: 0.8, maxvolume: 1.0, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				sheila1harmonic: {clip: "sheila1", minvolume: 0.8, maxvolume: 1.1, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				sheila2: {clip: "sheila2", minvolume: 0.8, maxvolume: 1.0  },
				cisterncello: {clip: "cisterncello", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(8,38)/10 } },
				cisterncelloharmonic: {clip: "cisterncello", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randomharmonic()/6 } },
				kantela1: {clip: "kantela1", minvolume: 0.5, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/8 } },
				kantela2: {clip: "kantela2", minvolume: 0.5, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/6 } },
				piano1: {clip: "piano1", minvolume: 0.3, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				piano1low: {clip: "piano1", minvolume: 0.3, maxvolume: 0.9, playbackRate: () => { return z.tools.randomlowharmonic()/10 } },
				kantelarandom: {clip: "kantela", minvolume: 0.5, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(2,28)/10 } },
				piano1random: {clip: "piano1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(2,48)/10 } },
				cello_pitch1: {clip: "cello_pitch1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				cello_pitch1I: {clip: "cello_pitch1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.I(100) / 100 } },
				cello_pitch1random: {clip: "cello_pitch1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(6,14)/10 } },
				cello_pitch1harmonic: {clip: "cello_pitch1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				cello_pitch1IV: {clip: "cello_pitch1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.IV(100) / 100 } },
				cello_pitch1V: {clip: "cello_pitch1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.V(100) / 100 } },
				clarinet1: {clip: "clarinet1",minvolume: 0.5, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				clarinethighbuzz: {clip: "clarinet1",minvolume: 0.1, maxvolume: 0.4, playbackRate: () => { return z.tools.randominteger(38,40)/10 } },
				clarinetI: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.I(100) / 100 } },
				clarinetIII: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.III(100) / 100 } },
				clarinetII: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.II(100) / 100 } },
				clarinetIV: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.IV(100) / 100 } },
				clarinetV: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.V(100) / 100 } },
				clarineti: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.i(100) / 100 } },
				clarinetvii: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.vii(100) / 100 } },
				clarinetVIII: {clip: "clarinet1",minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.data.sounds.intervals.VIII(100) / 100 } },
				icebowedvibesI: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.I(100) / 100 } },
				icebowedvibesIII: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.III(100) / 100 } },
				icebowedvibesII: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.II(100) / 100 } },
				icebowedvibesIV: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.IV(100) / 100 } },
				icebowedvibesV: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.V(100) / 100 } },
				icebowedvibesi: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.i(100) / 100 } },
				icebowedvibesvii: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.3, playbackRate: () => { return z.data.sounds.intervals.vii(100) / 100 } },
				icebowedvibesVIII: {clip: "icebowedvibes1", minvolume: 0.1, maxvolume: 0.6, playbackRate: () => { return z.data.sounds.intervals.VIII(100) / 100 } },
				thunk: {clip: "thunk", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				birds4: {clip: "birds4",minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(4, 24)/10 } },
				birds5: {clip: "birds5",minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(4, 24)/10 } },
				birds6: {clip: "birds6",minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(4, 24)/10 } },
				meow: {clip: "meow",minvolume: 0.6, maxvolume: 1.0, playbackRate: () => { return z.tools.randominteger(1, 9)/10 } },
				meowlow: {clip: "meow",minvolume: 0.8, maxvolume: 1.0, playbackRate: () => { return z.tools.randominteger(1,4)/10 } },
				crow: {clip: "crow", minvolume: 0.8, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(6, 18)/10 } },
				bird0: {clip: "bird0", minvolume: 0.8, maxvolume: 1.0 },
				bird1: {clip: "bird1", minvolume: 0.8, maxvolume: 1.0 },
				scrapingrandom: {clip: "scraping", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(4, 48)/10 } },
				scrapingrandom2: {clip: "scraping", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(4, 88)/10 } },
				scrapingharmonic: {clip: "scraping", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				cowbellrandom: {clip: "cowbell", minvolume: 0.6, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(4, 48)/10 } },
				cowbellharmonic: {clip: "cowbell", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				silobirds: {clip: "silobirds", minvolume: 0.4, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(3,18)/10 } },
				bird1random: {clip: "bird1", minvolume: 0.8, maxvolume: 1.0, playbackRate: () => { return z.tools.randominteger(6, 18)/10 } },
				bird1harmonic: {clip: "bird1", minvolume: 0.8, maxvolume: 1.0, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				bird2: {clip: "bird2", minvolume: 0.8, maxvolume: 1.0 },
				bird3: {clip: "bird3", minvolume: 0.8, maxvolume: 1.0 },
				birdtheme: {clip: "birdtheme", minvolume: 0.5, maxvolume: 0.9, },
				bell2: {clip: "bell2", minvolume: 0.5, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(5,20)/10 } },
				bell6: {clip: "bell6", minvolume: 0.5, maxvolume: 0.9, playbackRate: () => { return z.tools.randominteger(5,20)/10 } },
				bell11: {clip: "bell11", minvolume: 0.5, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(4,13)/10 } },
				bell13: {clip: "bell13", minvolume: 0.2, maxvolume: 0.4, playbackRate: () => { return z.tools.randominteger(6,18)/10 } },
				bell13harmonic: {clip: "bell13", minvolume: 0.2, maxvolume: 0.4, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				longbell: {clip: "longbell", minvolume: 0.4, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(9,18)/10 } },
				bell11low: {clip: "bell11", minvolume: 0.5, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(2,6)/10 } },
				weatherradio1: {clip: "weatherradio1", minvolume: 0.2, maxvolume: 0.4,  playbackRate: () => { return z.tools.randominteger(6,12)/10 }  },
				icebowedvibes1: {clip: "icebowedvibes1", minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				icebowedvibes1high: {clip: "icebowedvibes1", minvolume: 0.2, maxvolume: 0.6, playbackRate: () => { return z.tools.randomharmonic()/6 } },
				icebowedvibes1low: {clip: "icebowedvibes1", minvolume: 0.2, maxvolume: 0.4, playbackRate: () => { return z.tools.randominteger(5,10)/10 } },
				icebowedcymbal2: {clip: "icebowedcymbal2", minvolume: 0.3, maxvolume: 0.4, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				train: {clip: "train", minvolume: 0.3, maxvolume: 0.6, playbackRate: () => { return z.tools.randominteger(6,18)/10 } },
				fan: {clip: "fan", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(6,20)/10 } },
				surf: {clip: "surf", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randominteger(4,20)/10 } },
				silencebird1random: {clip: "bird1", minvolume: 0.1, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(6, 18)/10 } },
				silencetrain: {clip: "train", minvolume: 0.1, maxvolume: 0.4 },
				silencefan: {clip: "fan", minvolume: 0.1, maxvolume: 0.4 },
				silencesurf: {clip: "surf", minvolume: 0.1, maxvolume: 0.4 },
				silencetrainpitched: {clip: "train", minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(6,18)/10 } },
				silencefanpitched: {clip: "fan", minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(6,20)/10 } },
				silencesurfpitched: {clip: "surf", minvolume: 0.2, maxvolume: 0.5, playbackRate: () => { return z.tools.randominteger(4,20)/10 } },
				mags1: {clip: "mags1", minvolume: 0.3, maxvolume: 0.8 },
				mags1harmonic: {clip: "mags1", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randomlowharmonic()/10 } },
				mags2harmonic: {clip: "mags2", minvolume: 0.3, maxvolume: 0.8, playbackRate: () => { return z.tools.randomlowharmonic()/10 } },
				submarineecho1: {clip: "submarineecho", minvolume: 0.2, maxvolume: 0.8 },
				submarineecho2: {clip: "submarineecho",  minvolume: 0.2, maxvolume: 0.8, playbackRate: () => { return z.tools.randomharmonic()/10 } },
				submarineecho3: {clip: "submarineecho",  minvolume: 0.2, maxvolume: 0.8, playbackRate: () => { return z.tools.randomlowharmonic()/14 } },
			},
			intervals: {
				lowi: function(basetone){ return Math.floor(basetone/4) },
				i: function(basetone){ return Math.floor(basetone/2) },
				I: function(basetone){ return Math.floor(basetone/1) },
				II: function(basetone){ return Math.floor(basetone*9/8) },
				III: function(basetone){ return Math.floor(basetone*5/4) },
				iii: function(basetone){ return Math.floor(basetone*6/5) },
				IV: function(basetone){ return Math.floor(basetone*4/3) },
				V: function(basetone){ return Math.floor(basetone*3/2) },
				VI: function(basetone){ return Math.floor(basetone*5/3) },
				VII: function(basetone){ return Math.floor(basetone*15/8) },
				vii: function(basetone){ return Math.floor(basetone*9/5) },
				VIII: function(basetone){ return Math.floor(basetone*2) },
			},
			pools: {
				silence0: ["silencetrain","silencefan","silencesurf"],
				silence1: ["silencetrainpitched","silencefanpitched","silencesurfpitched"],
				ocean0: ["weatherradio1", "train", "fan", "surf"],
				ocean1: ["train", "fan", "surf"],
				ocean2: ["fan", "surf"],
				ocean3: ["train", "weatherradio1", "train", "fan", "surf", "silencetrainpitched","silencefanpitched","silencesurfpitched"],
				bells0: ["bell2", "bell6", "bell11"],
				bells1: ["bell11"],
				bowed0: ["icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"],
				bowed1: ["icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"],
				bowed2: ["cello_pitch1", "cello_pitch2", "cello_pitch3", "icebowedvibes1"],
				bowed3: ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V", "icebowedvibes1"],
				bowed4: ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV"],
				bowed5: ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesIV", "icebowedvibesV"],
				piano: ["piano1low", "piano1random", "piano1"],
				talk0: ["thunk"],
				talk1: ["typewriter1"],
				talk2: ["thunk","typewriter1"],
				talk3: ["surf", "train", "fan", "thunk"],
				talk4: ["birds4","birds5","birds6"],
				pitch0: ["clarinet1"],
				pitch1: ["clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV"],
				pitch2: ["clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV"],
				buzz0: ["clarinethighbuzz", "icebowedvibes1high"],
				buzz1: ["cisterncello", "cisterncelloharmonic"],
				scraping0: ["scrapingrandom2", "scrapingrandom","scrapingharmonic"],
				meow0: ["meow", "meowlow"],
				birds0: ["bird0", "bird1", "bird2", "bird3"],
				knocking0: ["knocking1"],
				knocking1: ["knocking2"],
				kantela: ["kantela1", "kantela2"],
				cellobells: ["cello_pitch4", "cello_pitch5"]
			},
			playlists: {
				fieldtrials: [ 
					["bell2", "bell6", "bell11", "silencesurf"], 
					["silencetrain","silencefan","bell11"],
					["surf","bird0", "bird1", "bird2", "bird3"], 
					["silencesurfpitched", "silencefanpitched","bird1random"], 
					["weatherradio1", "train", "fan", "surf"],  
					["silencefan","silencesurf","icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"], 
					["silencefan","icebowedvibes1high"], ["typewriter1"], ["thunk"], 
					["birds4","birds5","birds6"], 
					["silencesurf","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"], 
					["silencetrain","cello_pitch1harmonic"], ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V"] 
				],
				road: [
					["silencetrain","silencefan","bell11"], 
					["silencesurfpitched", "silencefanpitched","bird1random"], 
					["weatherradio1", "train", "fan", "surf"],  
					["silencefan","silencesurf","icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"], 
					["silencetrain","cello_pitch1harmonic"], ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V"] 
				],
				zinnias: [ 
					["bell2", "bell6", "bell11", "silencesurf"], ["silencetrain","silencefan","bell11"], 
					["weatherradio1", "train", "fan", "surf"],  
					["silencefan","silencesurf","icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"],  
					["silencefan","icebowedvibes1high"], ["typewriter1"], ["thunk"], 
					["silencesurf","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"]
				], 
				core: [ ["bell2", "bell6", "bell11"], ["bell11"], ["weatherradio1", "train", "fan", "surf"], ["icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"],["weatherradio1", "train", "fan", "surf"],  ["typewriter1"], ["surf", "icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"], ["thunk"], ["typewriter1"], ["bell2", "bell6", "bell11"],  ["surf", "fan"], ["thunk", "weatherradio1"], [ "weatherradio1", "train", "fan", "surf" ], ["silencetrainpitched","silencefanpitched","silencesurfpitched", "bell11"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","weatherradio1", "train", "fan", "surf"], ["train", "silencetrainpitched","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"], ["train", "weatherradio1", "train", "fan", "surf", "silencetrainpitched","silencefanpitched","silencesurfpitched"] ],
				ocean: [ ["weatherradio1", "train", "fan", "surf"], ["weatherradio1", "train", "fan", "surf"],  ["surf", "icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"], ["surf", "fan"], ["thunk", "weatherradio1"], [ "weatherradio1", "train", "fan", "surf" ], ["silencetrainpitched","silencefanpitched","silencesurfpitched", "bell11"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","weatherradio1", "train", "fan", "surf"], ["train", "silencetrainpitched","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"], ["train", "weatherradio1", "train", "fan", "surf", "silencetrainpitched","silencefanpitched","silencesurfpitched"] ],
				cellocore: [ ["weatherradio1", "train", "fan", "surf"], ["weatherradio1", "train", "fan", "surf"],  ["surf", "icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"], ["thunk"], ["typewriter1"], ["surf", "fan"], ["thunk", "weatherradio1"], ["train", "silencetrainpitched", "cello_pitch1", "cello_pitch2", "cello_pitch3", "icebowedvibes1"], ["silencetrainpitched", "cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V", "icebowedvibes1"], [ "weatherradio1", "train", "fan", "surf" ], ["silencetrainpitched","silencefanpitched","silencesurfpitched", "bell11"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","weatherradio1", "train", "fan", "surf"], ["train", "silencetrainpitched","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"], ["train", "weatherradio1", "train", "fan", "surf", "silencetrainpitched","silencefanpitched","silencesurfpitched"] ],
				celloclarinetcore: [ ["weatherradio1", "train", "fan", "surf"], ["weatherradio1", "train", "fan", "surf"],  ["surf", "icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"], ["thunk"], ["typewriter1"], ["surf", "fan"], ["thunk", "weatherradio1"], ["train", "silencetrainpitched", "cello_pitch1", "cello_pitch2", "cello_pitch3", "icebowedvibes1"], ["silencetrainpitched", "cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V"], [ "weatherradio1", "train", "fan", "surf" ], ["silencetrainpitched","silencefanpitched","silencesurfpitched", "bell11"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","weatherradio1", "train", "fan", "surf"], ["train", "silencetrainpitched","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"], ["train", "weatherradio1", "train", "fan", "surf", "silencetrainpitched","silencefanpitched","silencesurfpitched"], ["clarinet1"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV", "weatherradio1", "train", "fan", "surf"] ],
				clarinet: [["clarinet1"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV"], ["silencetrainpitched","silencefanpitched","silencesurfpitched","clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV", "weatherradio1", "train", "fan", "surf"] ],
				bowedvibes: [ ["train", "silencetrainpitched","icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"] ],
				cello: [ ["train", "silencetrainpitched", "cello_pitch1", "cello_pitch2", "cello_pitch3", "icebowedvibes1"], ["silencetrainpitched", "cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V", "icebowedvibes1"], ["silencetrainpitched", "cello_pitch1", "cello_pitch1I", "cello_pitch1IV"] ],
				talk: [  ["thunk"], ["thunk","typewriter1"], ["bell2", "bell6", "bell11"], ["thunk"], ["typewriter1"], ["surf"], ["surf", "train", "fan", "thunk"], ["typewriter1"], ["thunk"], ["typewriter1"], ["thunk"] ],
				buzzmeow0: [ ["meow", "meowlow","clarinethighbuzz"] ],
				background0: [ ["weatherradio1", "train", "fan", "surf"], ["train", "silencetrainpitched","silencefanpitched","silencesurfpitched"], ["silencetrain","silencefan","silencesurfpitched"], ["silencetrain","silencefan","silencesurf", "fan"], ["silencefan","silencesurf", "surf"] ],
				talking: [ ["birds4","birds5","birds6"], ["thunk"], ["typewriter1"],  ["birds4","birds5","birds6", "crow"], ["thunk", "typewriter1"]],
				//pools
				silence0: [ ["silencetrain","silencefan","silencesurf"] ],
				silence1: [ ["silencetrainpitched","silencefanpitched","silencesurfpitched"] ],
				ocean0: [ ["weatherradio1", "train", "fan", "surf"] ],
				ocean1: [ ["train", "fan", "surf"] ],
				ocean2: [ ["fan", "surf"] ],
				ocean3: [ ["train", "weatherradio1", "train", "fan", "surf", "silencetrainpitched","silencefanpitched","silencesurfpitched"] ],
				bells0: [ ["bell2", "bell6", "bell11"] ],
				bells1: [ ["bell11"] ],
				bowed0: [ ["icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesi","icebowedvibesIV", "icebowedvibesV"] ],
				bowed1: [ ["icebowedvibes1", "icebowedvibes1", "icebowedcymbal2"] ],
				bowed2: [ ["cello_pitch1", "cello_pitch2", "cello_pitch3", "icebowedvibes1"] ],
				bowed3: [ ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "cello_pitch1V", "icebowedvibes1"] ],
				bowed4: [ ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV"] ],
				bowed5: [ ["cello_pitch1", "cello_pitch1I", "cello_pitch1IV", "icebowedvibesI", "icebowedvibesi", "icebowedvibesII", "icebowedvibesI", "icebowedvibesIV", "icebowedvibesV"] ],
				talk0: [ ["thunk"] ],
				talk1: [ ["typewriter1"] ],
				talk2: [ ["thunk","typewriter1"] ],
				talk3: [ ["surf", "train", "fan", "thunk"] ],
				talk4: [ ["birds4","birds5","birds6"] ],
				pitch0: [ ["clarinet1"] ],
				pitch1: [ ["clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV"] ],
				pitch2: [ ["clarinetI", "clarineti", "clarinetI", "clarineti","clarinetI", "clarineti","clarinetIV", "clarinetV"] ],
				buzz0: [ ["clarinethighbuzz"] ],
				meow0: [ ["meow", "meowlow"] ],
				meowvibelow: [["icebowedvibesi", "meowlow"]],
				meowcello: [["cello_pitch1", "cello_pitch1IV", "cello_pitch1V", "meow", "meowlow"]],
				map3: [  ["piano1low"], [ "piano1random", "accordion"], ["accordion"], ["accordion", "knocking1"], ["knocking1"], ["piano1"],  ["piano1", "bird1harmonic"], ["piano1low"], ["longbell"], ["bell11low"], ["cello_pitch1I"], ["cello_pitch3", "cello_pitch2"], ["cello_pitch2"], ["cello_pitch1harmonic"], 
					["bird1harmonic"], [ "submarineecho1"], [ "submarineecho2"],[ "submarineecho3"], 
					["meow", "meow","meowlow"], ["mags1harmonic", "accordion"], ["mags1harmonic"], ["mags2harmonic"], ["mags1","cello_pitch1harmonic"], ["longbell"], ["bell11"], ["accordion", "bird1harmonic"], ["bird1harmonic"], ["piano1"],
					["piano1low"], [ "piano1random"], ["piano1", "bird1harmonic"], ["piano1low"], ["mags1harmonic"], ["cello_pitch1I"], ["cello_pitch3", "cello_pitch2"], ["cello_pitch2"], ["cello_pitch1harmonic"], 
					["mags1harmonic"], ["mags2harmonic"], ["mags1","cello_pitch1harmonic"], ["bird1harmonic"], ["piano1"] 
				],
				map4: [  //stripped down map3 sound
					["piano1low"], [ "piano1random"], ["knocking1"], ["piano1"],  ["piano1", "bird1harmonic"], ["piano1low"], 
					["bell11"], ["bell11low"], 
					["cello_pitch1I"], ["cello_pitch3", "cello_pitch2"], ["cello_pitch2"], 
					["cello_pitch1harmonic"], ["bird1harmonic"], 
					["mags1harmonic"], ["mags2harmonic"], ["mags1","cello_pitch1harmonic"], ["bell11"], ["bird1harmonic"], ["piano1"],
					["piano1low"], [ "piano1random"], ["piano1", "bird1harmonic"], ["piano1low"], ["mags1harmonic"], 
					["cello_pitch1I"], ["cello_pitch3", "cello_pitch2"], ["cello_pitch2"], ["cello_pitch1harmonic"], 
					["mags1harmonic"], ["mags2harmonic"], ["mags1","cello_pitch1harmonic"], ["bird1harmonic"], ["piano1"] 
				],
			}
		},
	}
};
// blueprint.score.oscilloscope.tones = Object.keys(z.data.sounds.intervals).reduce( (obj, key) => {
// 	return obj[key] = z.data.sounds.intervals[key](blueprint.score.oscilloscope.core);
// }, {});